[tools]
go = "latest"
node = "22"
typescript = "latest"
terraform = "latest"
python = "latest"

neovim = "latest"
lua = "5.1"
luarocks = "5.1"

peco = "latest"
ripgrep = "latest"
lazygit = "latest"
gh = "latest"
ghq = "latest"
oxker = "latest"

[env]

